# Generated by Django 6.0.1 on 2026-02-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
