# Generated by Django 6.0.1 on 2026-02-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_avatar_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='brain_type',
            field=models.CharField(blank=True, choices=[('overthinker', 'Overthinker'), ('flow', 'Go with the flow'), ('spreadsheet', 'Spreadsheet human'), ('see_what_happens', 'Wait and see'), ('delulu', 'Delulu but Functional'), ('chaos', 'Chaos Processor'), ('wifi', 'Emotionally Wi-Fi Dependent'), ('npc', 'NPC With Anxiety DLC')], max_length=50),
        ),
    ]
