# Generated by Django 6.0.1 on 2026-02-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_bio_alter_profile_brain_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='trust_score',
            new_name='lore_score',
        ),
    ]
