# Generated by Django 6.0.1 on 2026-02-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_trust_score_profile_lore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='brain_type_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vibe_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
