# Generated by Django 6.0.1 on 2026-02-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_brain_type_description_profile_vibe_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lore_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
