# Generated by Django 6.0.1 on 2026-02-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_privacy_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_nickname_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lore_score',
            field=models.IntegerField(default=1),
        ),
    ]
