# Generated by Django 6.0.1 on 2026-02-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_last_nickname_change_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='streak',
            new_name='current_streak_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_nickname_change',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_freeze_grant',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_freezes',
            field=models.IntegerField(default=0),
        ),
    ]
