# Generated by Django 6.0.1 on 2026-02-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_streak_profile_current_streak_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='campus',
            field=models.CharField(blank=True, default='Main Campus', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='matching_cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
