# Generated by Django 6.0.1 on 2026-02-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_campus_profile_matching_cooldown_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
    ]
