# Generated by Django 5.2.11 on 2026-02-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_is_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_secret',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
