# Generated by Django 6.0.1 on 2026-02-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending_vote', 'Pending Vote'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_vote', max_length=20),
        ),
    ]
