# Generated by Django 5.2.11 on 2026-02-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_matchchatmessage_id_alter_matchreport_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='compatibility_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
