# Generated by Django 6.0.1 on 2026-02-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpost',
            name='content',
            field=models.TextField(max_length=999),
        ),
    ]
