# Generated by Django 6.0.1 on 2026-02-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_alter_postreaction_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='anon_emoji',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='wallpost',
            name='anon_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='wallpost',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
